### ISSUE TITLE
### CI/CD

### ISSUE THREAD

**Issue by psimk** [mediamonks/porter#2]
Setup Github Actions for publishing new releases and testing each skeleton on a different node version

**Comment by crevulus** [comment]
Can you lay out exactly what steps we need here? I have a couple of scripts we should be able to adapt.

**Comment by psimk** [comment]
@crevulus
I updated the description, hope the task is a bit clearer now :)

**Comment by MickJasker** [comment]
You can use the release functionality to make this easier: 

```yaml
name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          always-auth: true
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Upgrade version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version --no-git-tag-version ${{ github.event.release.tag_name }}
          git add .
          git commit -m "Release version ${{ github.event.release.tag_name }}"
          git push
      - name: Publish to NPM
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

The downside is that you need to disable branch protections to make the commit on the main branch
